In [1]:
                #          <==============  NUMPY ==========>
                #                   -------------lab_7 --------------

In [3]:
# Q1 Create a Numpy array with numbers 1 to 101

import numpy as np

num = np.arange(1, 101)
print(num)

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]


In [5]:
# Q2 Reshape the array into a 10,10 array

arr= np.arange(1 , 101)
arr_reshaped = arr.reshape(10,10)
print(arr_reshaped)

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]


In [7]:
# Q3 Calculate the sum of each row

row_sums = np.sum(arr_reshaped, axis=1)
print(row_sums)

[ 55 155 255 355 455 555 655 755 855 955]


In [11]:
# Q4 Find the row with the maximum sum

max_sum_row = np.argmax(row_sums)

print("Array:")
print(arr_reshaped)
print()
print("Row Sums:")
print(row_sums)
print()
print("Row with Mamimum Sum:",max_sum_row)

Array:
[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]

Row Sums:
[ 55 155 255 355 455 555 655 755 855 955]

Row with Mamimum Sum: 9


In [13]:
# Q5 Create a 2D Numpy array with dimension 5*5
arr = np.random.randint(1,10,(5,5))
print("Original Array:")
print(arr)
mean_value = np.mean(arr[:-1])

print("Mean Value")
print(arr)

Original Array:
[[2 7 4 2 5]
 [4 5 7 2 2]
 [5 2 8 5 5]
 [9 1 8 2 7]
 [4 3 9 2 3]]
Mean Value
[[2 7 4 2 5]
 [4 5 7 2 2]
 [5 2 8 5 5]
 [9 1 8 2 7]
 [4 3 9 2 3]]


In [15]:
'''Task 1: Creating and Manipulating Arrays
Task: Create different types of arrays and perform basic operations.
Instructions:
1. Create an array of zeros with shape (3, 3).
2. Create an array of ones with shape (2, 4).
3. Create an array with values from 10 to 50, with a step of 10.
4. Add 5 to each element of the array created in step 3. '''

# 1. Create an array of zeros with shape (3, 3).
zeros_array = np.zeros((3,3))
print(zeros_array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [17]:
# 2. Create an array of ones with shape (2, 4).
arr = np.ones((2,4))
print(arr)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [19]:
# 3. Create an array with values from 10 to 50, with a step of 10.
arr = np.arange(10,51 , 10)
print(arr)

[10 20 30 40 50]


In [21]:
# 4. Add 5 to each element of the array created in step 3.
array = np.arange(10, 51, 10)

updated_array = array + 5

print("Original array:")
print(array)

print("\nArray after adding 5 to each element:")
print(updated_array)

Original array:
[10 20 30 40 50]

Array after adding 5 to each element:
[15 25 35 45 55]


In [23]:
''' Task 2: Indexing and Slicing
Task: Practice indexing and slicing arrays.
Instructions:
1. Create an array [10, 20, 30, 40, 50, 60].
2. Slice the array to get the first three elements.
3. Slice the array to get the last three elements.
4. Use advanced indexing to get the elements at indices 1, 3, and 5. '''

# 1. Create an array [10, 20, 30, 40, 50, 60].
array = np.array([10, 20, 30, 40, 50, 60])
print(array)

[10 20 30 40 50 60]


In [25]:
# 2. Slice the array to get the first three elements.
array = np.arange(10, 55, 10)

first_three_elements = array[:3]

print(first_three_elements)

[10 20 30]


In [27]:
# 3. Slice the array to get the last three elements.
array = np.arange(10, 55, 10)

first_last_elements = array[-3:]

print(first_last_elements)

[30 40 50]


In [51]:
# 4. Use advanced indexing to get the elements at indices 1, 3, and 5.
import numpy as np

array = np.arange(10, 51, 10)

indices = [1, 3]
selected_elements = array[indices]

print(selected_elements)


[20 40]


In [53]:
''' Task 3: Array Shape and Reshape.
Task 4: Array Shape and Reshape
Task: Reshape arrays and explore different shapes.
Instructions:
1. Create an array with values from 1 to 12.
2. Reshape it into a 3x4 matrix.
3. Reshape the same array into a 2x6 matrix.
4. Flatten the reshaped 3x4 matrix back into a 1D array. '''

# 1. Create an array with values from 1 to 12.
array = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(array)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [55]:
# 2. Reshape it into a 3x4 matrix.
matrix = np.arange(1, 13)
matrix_reshaped = matrix.reshape(3,4)
print(matrix_reshaped)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [57]:
# 3. Reshape the same array into a 2x6 matrix. 
matrix = np.arange(1, 13)
matrix_reshaped = matrix.reshape(2,6)
print(matrix_reshaped)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [59]:
# 4. Flatten the reshaped 3x4 matrix back into a 1D array.
matrix = np.arange(1, 13)
reshaped_matrix = matrix.reshape(3,4)
flattened_matrix = reshaped_matrix.flatten()

print(flattened_matrix)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [61]:
''' Task 4: Mathematical Operations
Task: Perform mathematical operations on arrays.
Instructions:
1. Create an array [10, 20, 30, 40, 50].
2. Calculate the sum of all elements.
3. Calculate the mean of the array.
4. Find the standard deviation. '''

# 1. Create an array [10, 20, 30, 40, 50].
array = np.array([10,20,30,40,50])
print(array)

[10 20 30 40 50]


In [63]:
# 2. Calculate the sum of all elements.
array = np.sum([10,20,30,40,50])
total_sum = np.sum(array)
print(f"Sum: {total_sum}")

Sum: 150


In [65]:
# 3. Calculate the mean of the array.
array = np.mean([10,20,30,40,50])
total_mean = np.mean(array)
print(f"mean: {total_mean}")

mean: 30.0


In [67]:
# 4. Find the standard deviation.
array = np.std([10,20,30,40,50])
std_deviation = np.std(array)
print(f"Standard Deviation: {std_deviation}")

Standard Deviation: 0.0


In [ ]:
                               #    <============== LAB_7 COMPLETE ==========>